/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'inagakikenichi' at '16/02/26 19:26' with Gradle 2.4
 *
 * @author inagakikenichi, @date 16/02/26 19:26
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
